In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, mean_absolute_error, mean_squared_error,classification_report
from sklearn.linear_model import LinearRegression

Load the csv file

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/EWU_Summer2025/CSE303_DMIM_Summer2025/Labs/synthetic_dataset.csv')
df

Display the first 15 rows of the dataset.

In [ ]:
df.head(15)

,Experience,Education,Department,Projects_Completed,Training_Hours,Performance_Score
0,7.0,Bachelor,Sales,28.0,35.0,112.836851
1,4.0,PhD,Engineering,28.0,27.0,104.791269
2,13.0,PhD,Engineering,24.0,23.0,113.136307
3,11.0,Master,Sales,19.0,23.0,104.239902
4,8.0,PhD,Engineering,22.0,75.0,104.025511
5,NaN,Bachelor,Sales,12.0,44.0,91.462814
6,5.0,NaN,Engineering,8.0,86.0,70.353345
7,7.0,NaN,Engineering,17.0,115.0,89.015870
8,10.0,Bachelor,HR,24.0,86.0,103.622347
9,3.0,PhD,HR,13.0,NaN,80.578435
10,7.0,PhD,Engineering,7.0,112.0,71.363447
11,11.0,Master,Sales,3.0,51.0,82.758257
12,11.0,PhD,HR,10.0,69.0,85.165134
13,8.0,Bachelor,Engineering,23.0,80.0,102.861983
14,5.0,NaN,Sales,14.0,70.0,81.832076

Display the last 15 rows of the dataset.

In [ ]:
df.tail(15)

,Experience,Education,Department,Projects_Completed,Training_Hours,Performance_Score
485,14.0,PhD,HR,23.0,104.0,113.890530
486,12.0,NaN,HR,4.0,NaN,80.288978
487,3.0,Master,HR,15.0,114.0,82.348289
488,7.0,PhD,Sales,13.0,74.0,79.355360
489,12.0,Bachelor,HR,13.0,67.0,94.317387
490,2.0,NaN,HR,18.0,101.0,77.415669
491,2.0,Master,HR,13.0,26.0,81.293400
492,7.0,Bachelor,HR,21.0,93.0,90.206803
493,6.0,NaN,Engineering,17.0,26.0,87.815827
494,3.0,NaN,HR,27.0,52.0,98.146579
495,9.0,Bachelor,Engineering,25.0,42.0,107.474129
496,10.0,NaN,Sales,25.0,104.0,104.593824
497,14.0,Master,HR,18.0,38.0,100.522453
498,13.0,Bachelor,Engineering,13.0,38.0,92.666024
499,6.0,NaN,Sales,24.0,55.0,100.641627

Check for any missing (null) values in the dataset (if needed).

In [ ]:
print(df.isnull().values.any())
print(df.isnull().sum())

True
Experience             20
Education             135
Department              0
Projects_Completed      0
Training_Hours         20
Performance_Score       0
dtype: int64

In [ ]:
df['Education'] = df['Education'].fillna('Unknown')
df['Training_Hours'] = df['Training_Hours'].fillna(0)
df['Experience'] = df['Experience'].fillna(0)
df

,Experience,Education,Department,Projects_Completed,Training_Hours,Performance_Score
0,7.0,Bachelor,Sales,28.0,35.0,112.836851
1,4.0,PhD,Engineering,28.0,27.0,104.791269
2,13.0,PhD,Engineering,24.0,23.0,113.136307
3,11.0,Master,Sales,19.0,23.0,104.239902
4,8.0,PhD,Engineering,22.0,75.0,104.025511
...,...,...,...,...,...,...
495,9.0,Bachelor,Engineering,25.0,42.0,107.474129
496,10.0,Unknown,Sales,25.0,104.0,104.593824
497,14.0,Master,HR,18.0,38.0,100.522453
498,13.0,Bachelor,Engineering,13.0,38.0,92.666024
499,6.0,Unknown,Sales,24.0,55.0,100.641627

Perform appropriate mapping if needed

In [ ]:
education_map = {'Bachelor': 0, 'Master': 1, 'PhD': 2, 'Unknown': 3}
department_map = {'Sales': 0, 'Engineering': 1, 'HR': 2}
df['Education'] = df['Education'].map(education_map)
df['Department'] = df['Department'].map(department_map)
df

,Experience,Education,Department,Projects_Completed,Training_Hours,Performance_Score
0,7.0,0,0,28.0,35.0,112.836851
1,4.0,2,1,28.0,27.0,104.791269
2,13.0,2,1,24.0,23.0,113.136307
3,11.0,1,0,19.0,23.0,104.239902
4,8.0,2,1,22.0,75.0,104.025511
...,...,...,...,...,...,...
495,9.0,0,1,25.0,42.0,107.474129
496,10.0,3,0,25.0,104.0,104.593824
497,14.0,1,2,18.0,38.0,100.522453
498,13.0,0,1,13.0,38.0,92.666024
499,6.0,3,0,24.0,55.0,100.641627

Run linear regression model on the dataset

In [ ]:
x = df.drop(columns = ['Performance_Score'])
y = df['Performance_Score']

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
print("x_train\n",x_train)
print("y_train\n",y_train)
print("x_test\n",x_test)
print("y_test\n",y_test)

x_train
      Experience  Education  Department  Projects_Completed  Training_Hours
249        12.0          3           0                28.0            85.0
433         3.0          2           2                20.0            97.0
19          6.0          3           2                 8.0           111.0
322        14.0          3           0                24.0            81.0
332         2.0          3           1                 8.0            56.0
..          ...        ...         ...                 ...             ...
106        13.0          3           1                26.0            78.0
270        14.0          0           1                24.0             0.0
348         8.0          1           1                19.0           109.0
435         1.0          3           0                 3.0            85.0
102         9.0          0           1                 7.0            71.0

[400 rows x 5 columns]
y_train
 249    119.200949
433     90.717319
19      67.286467
322    111.185032
332     68.411359
          ...
106    119.511273
270    118.453690
348     90.058946
435     50.941873
102     85.283167
Name: Performance_Score, Length: 400, dtype: float64
x_test
      Experience  Education  Department  Projects_Completed  Training_Hours
361        14.0          2           0                 7.0            92.0
73          0.0          0           2                17.0            34.0
374         4.0          3           1                24.0            57.0
155         8.0          1           1                 6.0            87.0
104         8.0          3           0                 6.0             0.0
..          ...        ...         ...                 ...             ...
347         6.0          3           2                24.0            40.0
86         10.0          0           1                 3.0            32.0
75          3.0          2           0                16.0           108.0
438         5.0          0           2                 7.0            57.0
15          4.0          2           0                14.0            38.0

[100 rows x 5 columns]
y_test
 361     87.789807
73      92.597217
374     86.968577
155     74.479751
104     81.739279
          ...
347    100.196514
86      78.688487
75      88.006191
438     69.190168
15      74.120101
Name: Performance_Score, Length: 100, dtype: float64

In [ ]:
lr = LinearRegression()
lr.fit(x_train, y_train)
lr_pred = lr.predict(x_test)
lr_pred

array([ 87.13442857,  78.87489574,  96.19398078,  75.64906569,
        75.17726318, 104.49658041,  79.94124573,  59.08431714,
        70.52756985,  86.68196232,  78.00366251,  83.8877337 ,
        65.58733851,  76.68761127,  95.54907371,  76.19457325,
       106.10832287,  92.06213498, 100.22681513,  72.92757231,
        84.13866257,  76.27594436,  97.23147202,  87.44564038,
       110.63398971,  86.5265439 , 104.53559042, 103.76677919,
       113.17501904, 116.41811617,  91.10650445,  76.036912  ,
        95.10711845, 108.27388092, 111.54641759,  75.41948873,
        93.7593665 , 113.87751699,  98.47813187,  77.00813833,
       101.68029551,  65.39324977, 112.32261465,  97.88561838,
       115.0568007 ,  65.26034114, 106.79591165,  75.75712867,
        59.46344436,  92.3413816 ,  83.74542787,  93.87602881,
        87.50109499, 102.37073978,  66.63099819,  90.60693923,
        73.54454636,  67.19473117,  99.13636431,  80.99335482,
        99.44595748,  70.00114504,  60.39904106,  72.4903842 ,
        83.61161356, 112.98910674,  87.59087566, 115.52985326,
        87.43777603,  72.98492281, 105.1690354 , 110.70463373,
        67.14075379, 100.18587439,  97.71418083,  94.41220204,
        86.41223522, 110.34228228,  83.47425113,  76.52788046,
       113.21363374,  84.15410845,  94.26850219, 109.54243789,
       101.60834067,  74.28270026, 115.9866884 ,  82.08911505,
       105.31813216,  87.30407679, 108.63407702,  97.32616125,
        94.00419958,  80.23419727,  84.71201862, 100.02082137,
        74.3629907 ,  81.93202238,  72.31474549,  80.47595948])

In [ ]:
lr_mae = mean_absolute_error(y_test, lr_pred)
lr_mse = mean_squared_error(y_test, lr_pred)
lr_rmse = np.sqrt(mean_squared_error(y_test, lr_pred))

print('MAE Linear Regression: ', lr_mae)
print('MSE Linear Regression: ', lr_mse)
print('RMSE Linear Regression: ', lr_rmse)

MAE Linear Regression:  4.626581425224374
MSE Linear Regression:  34.203147430626615
RMSE Linear Regression:  5.848345700334977